### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by hemanth** [jstransformers/meta#1]
Time for a logo?

**Comment by tunnckoCore** [comment]
here have some https://thenounproject.com, but custom would be great :)

**Comment by RobLoach** [comment]
> here have some https://thenounproject.com, but custom would be great also :)

Rather use something behind a permissive open source license. :wink:

**Comment by tunnckoCore** [comment]
> Rather use something behind a permissive open source license.

if we use some of them, we can add links, its not a problem https://github.com/datetime/meta/blob/master/logo-license.md

**Comment by ForbesLindesay** [comment]
I'd much prefer a custom logo, using a stock image is not really any better than no logo at all.  I don't mind stumping up a (small) amount of cash if someone knows a good designer.

**Comment by hemanth** [comment]
@stoeffel Do you have some time to cook a logo for us :) ?

**Comment by stoeffel** [comment]
@hemanth I will try.

**Comment by stoeffel** [comment]
![jstransformers](https://cloud.githubusercontent.com/assets/1217681/6996712/ffe92cf4-db97-11e4-9d8e-504c145453df.png)

How do you like this guys?

**Comment by hemanth** [comment]
:+1: Awesome! 

![](http://media.giphy.com/media/JMO4cIurdazV6/giphy.gif)

**Comment by RobLoach** [comment]
![http://cdn.smosh.com/sites/default/files/legacy.images/smosh-pit/062011/transformer-slam-dunk.gif](http://cdn.smosh.com/sites/default/files/legacy.images/smosh-pit/062011/transformer-slam-dunk.gif)

**Comment by ForbesLindesay** [comment]
That looks fantastic! So grateful right now. Do you have an SVG of it we can use?

**Comment by hemanth** [comment]
@ForbesLindesay It would nice to create a sub org, say `logos` and add @stoeffel as a owner to it?

**Comment by stoeffel** [comment]
> It would nice to create a team, say logos and add @stoeffel as a owner to it

That would be great!
![transformer-surf](https://cloud.githubusercontent.com/assets/1217681/7001132/f81823b8-dc32-11e4-9dc7-1a7bd24734e3.gif)

**Comment by stoeffel** [comment]
> Do you have an SVG of it we can use?

https://drive.google.com/folderview?id=0BwekZi_lbxSRfktVN1BfaHJ2UHN1VElrSW02Zzk3OW5Kb1JCVTVQNXo0WEhud0FJQW11MUk&usp=sharing

**Comment by TimothyGu** [comment]
@stoeffel for us poor students who don't have AI can you please embed the font in the SVG version? Thanks! (Right now the browser has to fallback on regular fonts for "JS")

**Comment by stoeffel** [comment]
@TimothyGu I updated the svg can you check again?

**Comment by TimothyGu** [comment]
@stoeffel 

Seems like you actually **embedded** the font…

I meant something like “Object to path” like in Inkscape, which hardcodes the glyphs into the SVG itself as regular paths, and not merely “attaching” the fonts in a `<font>` tag…

**Comment by stoeffel** [comment]
@TimothyGu oups... my brain is still sleeping :sleeping: . I updated it again.

**Comment by TimothyGu** [comment]
@stoeffel there we go. Thank you SO MUCH for the logo. Now *I* gotta sleep :wink:

**Comment by RobLoach** [comment]
@stoeffel Again, this is awesome :+1: Well done on getting this in.

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
@RobLoach np, I'm glad you guys like it so much :blush: 

As suggested by @hemanth it would be great if you would add me to a suborg, so I have my logo in the orgs list. But if that doesn't work for you it's no biggy.

**Comment by TimothyGu** [comment]
@stoeffel I have invited you to our owners team, both because you have added a JSX transformer and to troll you into adding more :wink:. Feel free to move your jstransformer-jsx under the umbrella of jstransformers.

Welcome aboard!

**Comment by stoeffel** [comment]
Cool, thanks a lot. Nice to join you. I will move my transformer over.
